import datetime as dt

from bs4 import BeautifulSoup

from app.parsers import sherdog


def test_event_parsing(sherdog_event):
    page_content, page_url = sherdog_event
    event_data = sherdog.extract_event_data(page_content, page_url)
    assert event_data == {
        "title": "UFC 214 Cormier vs. Jones 2",
        "organization": "Ultimate Fighting Championship (UFC)",
        "date": dt.date(2017, 7, 29),
        "location": "Honda Center / Anaheim / California / United States",
        "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
    }


def test_main_fight_parsing(sherdog_event):
    page_content, _ = sherdog_event
    soup = BeautifulSoup(page_content, "lxml")
    fights = sherdog._extract_main_fight_from_event(soup)
    assert fights == {
        "method": "no contest",
        "details": "overturned by csac",
        "result": "NC",
        "rounds": 3,
        "time": 13.016666666666666,
        "fighter": "/fighter/Jon-Jones-27944",
        "opponent": "/fighter/Daniel-Cormier-52311",
        "position": 1,
    }


def test_other_fights_parsing(sherdog_event):
    page_content, _ = sherdog_event
    soup = BeautifulSoup(page_content, "lxml")
    fights = sherdog._extract_other_fights_from_event(soup)
    assert fights == [
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 5,
            "time": 25.0,
            "fighter": "/fighter/Tyron-Woodley-42605",
            "opponent": "/fighter/Demian-Maia-14637",
            "position": 2,
        },
        {
            "method": "tko",
            "details": "knees",
            "result": "win",
            "rounds": 3,
            "time": 11.933333333333334,
            "fighter": "/fighter/Cristiane-Justino-14477",
            "opponent": "/fighter/Tonya-Evinger-18248",
            "position": 3,
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Robbie-Lawler-2245",
            "opponent": "/fighter/Donald-Cerrone-15105",
            "position": 4,
        },
        {
            "method": "ko",
            "details": "punches",
            "result": "win",
            "rounds": 1,
            "time": 0.7,
            "fighter": "/fighter/Volkan-Oezdemir-58503",
            "opponent": "/fighter/Jimi-Manuwa-37528",
            "position": 5,
        },
        {
            "method": "tko",
            "details": "punches",
            "result": "win",
            "rounds": 1,
            "time": 4.566666666666666,
            "fighter": "/fighter/Ricardo-Lamas-32051",
            "opponent": "/fighter/Jason-Knight-44957",
            "position": 6,
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Aljamain-Sterling-66313",
            "opponent": "/fighter/Renan-Barao-23156",
            "position": 7,
        },
        {
            "method": "submission",
            "details": "guillotine choke",
            "result": "win",
            "rounds": 3,
            "time": 12.983333333333334,
            "fighter": "/fighter/Brian-Ortega-65310",
            "opponent": "/fighter/Renato-Carneiro-61700",
            "position": 8,
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Calvin-Kattar-23782",
            "opponent": "/fighter/Andre-Fili-58385",
            "position": 9,
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Aleksandra-Albu-144949",
            "opponent": "/fighter/Kailin-Curran-62703",
            "position": 10,
        },
        {
            "method": "decision",
            "details": "split",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Jarred-Brooks-174665",
            "opponent": "/fighter/Eric-Shelton-86414",
            "position": 11,
        },
        {
            "method": "ko",
            "details": "punch",
            "result": "win",
            "rounds": 1,
            "time": 3.066666666666667,
            "fighter": "/fighter/Drew-Dober-23982",
            "opponent": "/fighter/Joshua-Burkman-10003",
            "position": 12,
        },
    ]


def test_fights_parsing(sherdog_event):
    page_content, page_url = sherdog_event
    fights = sherdog.extract_fights(page_content, page_url)
    assert fights == [
        {
            "method": "no contest",
            "details": "overturned by csac",
            "result": "NC",
            "rounds": 3,
            "time": 13.016666666666666,
            "fighter": "/fighter/Jon-Jones-27944",
            "opponent": "/fighter/Daniel-Cormier-52311",
            "position": 1,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "afd3bcdc64e748c682ca16571cc795c6",
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 5,
            "time": 25.0,
            "fighter": "/fighter/Tyron-Woodley-42605",
            "opponent": "/fighter/Demian-Maia-14637",
            "position": 2,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "2b98f294e5107ca9ec8deffdf3500dea",
        },
        {
            "method": "tko",
            "details": "knees",
            "result": "win",
            "rounds": 3,
            "time": 11.933333333333334,
            "fighter": "/fighter/Cristiane-Justino-14477",
            "opponent": "/fighter/Tonya-Evinger-18248",
            "position": 3,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "6d93b2aab27dfd083ab78253ae675dd6",
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Robbie-Lawler-2245",
            "opponent": "/fighter/Donald-Cerrone-15105",
            "position": 4,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "0b332aec900d7929eddeeca0e57abc95",
        },
        {
            "method": "ko",
            "details": "punches",
            "result": "win",
            "rounds": 1,
            "time": 0.7,
            "fighter": "/fighter/Volkan-Oezdemir-58503",
            "opponent": "/fighter/Jimi-Manuwa-37528",
            "position": 5,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "b333eb2594811f25fb883e5bdc3daf85",
        },
        {
            "method": "tko",
            "details": "punches",
            "result": "win",
            "rounds": 1,
            "time": 4.566666666666666,
            "fighter": "/fighter/Ricardo-Lamas-32051",
            "opponent": "/fighter/Jason-Knight-44957",
            "position": 6,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "e33ce5c4c65086793b02d924ffa343bd",
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Aljamain-Sterling-66313",
            "opponent": "/fighter/Renan-Barao-23156",
            "position": 7,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "2cc890dca0eedcc677e12bd75d757736",
        },
        {
            "method": "submission",
            "details": "guillotine choke",
            "result": "win",
            "rounds": 3,
            "time": 12.983333333333334,
            "fighter": "/fighter/Brian-Ortega-65310",
            "opponent": "/fighter/Renato-Carneiro-61700",
            "position": 8,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "d560cfb06143a99312e8a94e35c5b811",
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Calvin-Kattar-23782",
            "opponent": "/fighter/Andre-Fili-58385",
            "position": 9,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "d0d93dee674239407c0d524133159d00",
        },
        {
            "method": "decision",
            "details": "unanimous",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Aleksandra-Albu-144949",
            "opponent": "/fighter/Kailin-Curran-62703",
            "position": 10,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "c66ca3393a78b7a9d8d42754c602fdb2",
        },
        {
            "method": "decision",
            "details": "split",
            "result": "win",
            "rounds": 3,
            "time": 15.0,
            "fighter": "/fighter/Jarred-Brooks-174665",
            "opponent": "/fighter/Eric-Shelton-86414",
            "position": 11,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "d7061763b3f8c53f42836b92174f4cea",
        },
        {
            "method": "ko",
            "details": "punch",
            "result": "win",
            "rounds": 1,
            "time": 3.066666666666667,
            "fighter": "/fighter/Drew-Dober-23982",
            "opponent": "/fighter/Joshua-Burkman-10003",
            "position": 12,
            "url": "https://www.sherdog.com/events/UFC-214-Cormier-vs-Jones-2-57825",
            "title": "UFC 214 Cormier vs. Jones 2",
            "organization": "Ultimate Fighting Championship (UFC)",
            "date": dt.date(2017, 7, 29),
            "location": "Honda Center / Anaheim / California / United States",
            "id": "31c349aae85bbef0bc1716fbd84dfd01",
        },
    ]


def test_empty_webiste_fights_parsing():
    fights = sherdog.extract_fights(None, "")
    assert len(fights) == 0


def test_fighter_parsing(sherdog_fighter):
    page_content, page_url = sherdog_fighter
    fighter = sherdog.extract_fighter_info(page_content, page_url)
    assert fighter == {
        'fighter': 'https://www.sherdog.com/fighter/Jon-Jones-27944',
        'birth': '1987-07-19',
        'height': 6.4,
        'association': 'Jackson-Wink MMA', 
        'nationality': 'United States'
    }
